# Generated by Django 3.0.2 on 2020-01-11 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('image_height', models.IntegerField(default=0)),
                ('image_width', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, height_field='image_height', max_length=200, upload_to='clinics/%Y/%m/%d', width_field='image_width')),
                ('phone_number', models.IntegerField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('slug', models.SlugField(default=None, max_length=100, unique=True)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('proffesion', models.CharField(max_length=100)),
                ('image_height', models.IntegerField(default=50)),
                ('image_width', models.IntegerField(default=70)),
                ('image', models.ImageField(blank=True, height_field='image_height', max_length=200, upload_to='doctors/%Y/%m/%d', width_field='image_width')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic', to='clinic.Clinic')),
                ('username', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
